### ISSUE TITLE
[PE-D][Tester C] User guide is not specific about the functionality of find command variants.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F12-2/tp#371] opened 2024-11-08 18:22 UTC
From the user guide we have:

![image.png](https://raw.githubusercontent.com/uniqly/ped/main/files/3560cf3c-2928-41e7-9505-3664dba5e835.png)

For users reading the guide it is not clear if the command is meant to find students that match all the queries or any of the queries.

For instance, a user may run the command `fs q/CS2103-F12-1 q/consult` hoping to find only students in group `gn/CS2103-F12-1` that have scheduled a consult (tag `t/consult`) with them, but, after running the command, the displays all students in `gn/CS2103-F12-1` and all students with tag `t/consult`.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: uniqly/ped#4

**Comment by ghos7ie** [comment] 2024-11-10 08:21
Duplicate of #400

**Closed by ghos7ie** 2024-11-10 08:21 UTC
Labels: pe-d
