### ISSUE TITLE
[PE-D][Tester A] Incorrect Error Message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F12-2/tp#376] opened 2024-11-08 19:13 UTC
![image.png](https://raw.githubusercontent.com/LimErnest/ped/main/files/562b3f09-caf8-4aec-ac87-8d15c8572f6c.png)

the error message should show wrong format or additional prefix of e/ instead of treating the gn to be wrong

expected: wrong format error message

actual: wrong group name error message

steps to reproduce: enter `eg i/3 gn/cs2103-g12-12 e/e100000@u.nus.edu`

suggestion: parse all prefix in input and check if it matches the actual command

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: LimErnest/ped#8

**Comment by ghos7ie** [comment] 2024-11-11 09:54
duplicate of #359

**Closed by ghos7ie** 2024-11-11 09:54 UTC
Labels: pe-d
