### ISSUE TITLE
[PE-D][Tester D] Allowing Duplicate Student Numbers

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F12-2/tp#357] opened 2024-11-08 16:48 UTC
![image.png](https://raw.githubusercontent.com/wenjebs/ped/main/files/9c9eb393-2305-4b4b-9ca1-5dcf6ab800f1.png)
I was able to add students with same student numbers.

Steps to recreate :
1. Add student with a specific student number
2. Add another student with same student number but different name and email.

Expected :
Prevent user from creating student with existing student number

Actual :
Student was created.

Suggestion :
Add check for existing student numbers

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: wenjebs/ped#7

**Comment by ghos7ie** [comment] 2024-11-10 08:19
Duplicate of #361

**Closed by ghos7ie** 2024-11-10 08:19 UTC
Labels: pe-d
