### ISSUE TITLE
Bug: Update GUI to reflect the outcome of the undo/redo command

### ISSUE THREAD

**Issue by dez2003** [AY2425S1-CS2103-F12-2/tp#260] opened 2024-11-05 02:00 UTC
After typing the redo/undo command, the GUI should display the panel to show what has been undone/redone

**Comment by ghos7ie** [comment] 2024-11-05 09:54
@SooYap I will place in Planned Enhancement

I don't think it's difficult to implement but i'm afraid it might introduce more bugs~

**Comment by SooYap** [comment] 2024-11-05 10:06
@ghos7ie @dez2003 I think this is actually quite a complex enhancement to do.
Because versionhistory right now only stores each current state of the model and has no knowledge about which command was executed. So if we wanna make the GUI display the changes for undo/redo we need to change quite a few things, including the attributes stored by each version and the handling and storage of json etc. Not to mention the implementation of this is going to vary slightly for undo and redo too which might result in more additions.

So I think we can leave this for next week (shouldn't be a problem even with the feature freeze) and ya I do agree it might introduce some bugs too.

**Comment by ghos7ie** [comment] 2024-11-05 10:11
@SooYap i think this enhancement we can't do next week due to feature freeze

we can put into planned enhancement if it surfaces up during PE-D, else we will not mention since it isn't exactly a feature flaw that will get our marks deducted

Should it surface during the actual PE, we can maybe argue that it is a QOL enhancement, not a bug since the user just ran the command, they should be aware of what they ran under normal usage

**Comment by ghos7ie** [comment] 2024-11-05 10:12
I will remove the milestone tag for this so that we can remember it during the our post PE-D discussion

**Comment by SooYap** [comment] 2024-11-05 10:17
If I can think of a viable solution and implement it before this Thursday I'll do it because I think its a good feature to have although not completely necessary, if not we'll leave it for after the dry run or PE

**Comment by ghos7ie** [comment] 2024-11-10 10:20
Will not add into planned enhancement.

We can argue out of scope if this comes up during PE. Undo and redo functions usually assume that the user already knows their last action.

**Closed by ghos7ie** 2024-11-10 10:20 UTC
Labels: priority.High, severity.High, alpha-bug
