### ISSUE TITLE
[PE-D][Tester D] Duplicate emails allowed when adding students

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F12-2/tp#354] opened 2024-11-08 16:21 UTC
![image.png](https://raw.githubusercontent.com/wenjebs/ped/main/files/51e650ea-66a9-4884-bd23-256c2e644b06.png)

Perhaps should not be able to add students with same email?
I was able to add students with same email, as shown in screenshot above.

Suggestion :
Prevent user from adding students with same email.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: wenjebs/ped#5

**Comment by ghos7ie** [comment] 2024-11-10 08:18
Duplicate of #356

**Closed by ghos7ie** 2024-11-10 08:18 UTC
Labels: pe-d
