### ISSUE TITLE
[PE-D][Tester B] User guide for query command limitations

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F12-2/tp#395] opened 2024-11-08 23:30 UTC
![image.png](https://raw.githubusercontent.com/LiuYJ2002/ped/main/files/aeee3537-c308-490c-b0e1-04177f04a987.png)
It states that there are no limitations for `q/` but provided `q/Complete ip` as an incorrect example for users.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: LiuYJ2002/ped#13

**Comment by ghos7ie** [comment] 2024-11-09 07:18
Duplicate of #399

**Closed by ghos7ie** 2024-11-09 07:18 UTC
Labels: pe-d
